# Generated by Django 5.2.1 on 2025-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='founditem',
            name='contact_no',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
