# Generated by Django 5.2.1 on 2025-05-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0002_remove_founditem_created_at_founditem_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='founditem',
            name='contact',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_items/'),
        ),
    ]
