# Generated by Django 5.2.1 on 2025-05-24 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0003_remove_founditem_contact_no_founditem_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='contact',
        ),
        migrations.AddField(
            model_name='founditem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_images/'),
        ),
    ]
